print()
print()
print("Kalkuliere deinen Stundensatz als Selbständiger")
print("Bitte trage deine eigenen Zahlen ein")
print()
indicesPrefix = "€"
print("Kosten")
grossvalue = float(input("gewünschtes Bruttogehalt:              "))
socialinsuranceRate = 20
socialinsurance = ((grossvalue * socialinsuranceRate) / 100)
print("Sozialversicherungsbeiträge:          +", socialinsurance, indicesPrefix)
occupationalRate = 75.0
print("Berufsunfähigkeitsversicherung:       + ", occupationalRate, indicesPrefix)
occupational = ((grossvalue * 10) / 100)
print("Altersvorsorge (10%):                 +", occupational, indicesPrefix)
subtotal = (grossvalue + socialinsurance + occupational + occupationalRate)
print("Zwischensumme:                       =", subtotal, indicesPrefix)
print()
print("Auslastung im Jahr")

calendarDays = 360
calendarPrefix = "Tage"
weekendDays = 104
print("Kalendertage:                          ", calendarDays, calendarPrefix)
print("Wochenende:                            ", weekendDays, calendarPrefix)
holiday = float(input("Feiertage:                               "))
vacation = float(input("Urlaubstage:                             "))
sickleave = float(input("geschätzer Krankenstand:                 "))
education = float(input("Weiterbildungsmaßnahmen:                 "))
print("Arbeitstage pro Jahr:                  ",calendarDays - weekendDays - holiday - vacation - sickleave - education)
workdaysMonth = ((calendarDays - weekendDays - holiday - vacation - sickleave - education) / 12)
print("Arbeitstage pro Monat:                  ", workdaysMonth)
print()
utilization = float(input("Geschätzte Auslastung in %:             "))
utilizationMonth = round((workdaysMonth * utilization) / 100, 2)
print("Produktivität im Monat:                ", utilizationMonth)
print()
print("Weitere Kosten")
print("Trage deine Kosten für dieses Jahr ein:")
print()
rent = float(input("Miete:                                "))
marketing = float(input("Marketing:                            "))
management = float(input("Verwaltung:                           "))
supplier = float(input("Lieferanten:                          "))
compInsurance = float(input("Betr. Versicherungen:                 "))
finance = float(input("Finanzierungen:                       "))
workUtilities = float(input("Werkzeuge/Software:                   "))
extras = float(input("sonstige Ausgaben:                    "))
taxes = float(input("betr. Steuern:                        "))
totalCosts = round(rent + marketing + management + supplier + compInsurance + finance + workUtilities + extras + taxes, 2)
print("Gesamtkosten:                        ", totalCosts)
print()
print("Stundensatz errechnen:")
globalCosts = subtotal * 12 + totalCosts
print("Gesamtkosten:                       ", globalCosts)
billableWork = round((utilizationMonth * 12), 2)
print("Abrechenbare Arbeitsstunden:           ", billableWork)
print("Pro Arbeitstag:                      ", round(globalCosts / billableWork, 2))
workingHoursDaily = 8
print("Arbeitsstunden pro Tag:                 ", workingHoursDaily)
eachHour = round((globalCosts / billableWork) / workingHoursDaily, 2)
print()
billing = float(input("Finanzierungskosten  in %:               "))
revenue = float(input("Gewinnmarge          in %:               "))

netHourlyRate = round(eachHour * (1 + billing) * (1 + revenue), 2)
print("Netto-Stundensatz:                   ", netHourlyRate)
vat = round(netHourlyRate * 1.19, 2)
print("zzgl 19% MwSt.:                      ", vat)
